{% set version = "2.6.0" %}

package:
  name: python-coveralls
  version: {{ version }}

source:
  fn: python-coveralls-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/python-coveralls/python-coveralls-{{ version }}.tar.gz
  sha256: c0c9b246129bdf4c2e0f4a1b31962bb043b73030aa7a23f711561c1f6da8b0a5

build:
  number: 0
  skip: true  # [win]
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - coveralls = coveralls:wear

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pyyaml
    - requests
    - coverage ==4.0.3
    - six
    - sh

test:
  imports:
    - coveralls

  commands:
    - coveralls --help

about:
  home: http://github.com/z4r/python-coveralls
  license: Apache 2.0
  summary: 'Python interface to coveralls.io API\n'

extra:
  recipe-maintainers:
    - jakirkham
